// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'quotes-listing': string;
  'quotes-listing__quotes': string;
}
export const cssExports: CssExports;
export default cssExports;
